// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF2co4890jLtJtvfBvzc_fAbBJaJlso_A',
    appId: '1:45637135444:web:d36eeb179e73fd477e91c1',
    messagingSenderId: '45637135444',
    projectId: 'cone-1f0d5',
    authDomain: 'cone-1f0d5.firebaseapp.com',
    storageBucket: 'cone-1f0d5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8tfhYcoBXhNsPlBxeoq_ad5uPHH6gbMk',
    appId: '1:45637135444:android:37aa92de4a0ef0b27e91c1',
    messagingSenderId: '45637135444',
    projectId: 'cone-1f0d5',
    storageBucket: 'cone-1f0d5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF2co4890jLtJtvfBvzc_fAbBJaJlso_A',
    appId: '1:45637135444:web:be75c0b1e2beb6517e91c1',
    messagingSenderId: '45637135444',
    projectId: 'cone-1f0d5',
    authDomain: 'cone-1f0d5.firebaseapp.com',
    storageBucket: 'cone-1f0d5.firebasestorage.app',
  );
}
